
import React from 'react';
import { MangaScriptSection } from '../types';
import { Spinner } from './Spinner';

declare global {
  interface Window {
    jspdf: any;
  }
}

interface MangaViewerProps {
  script: MangaScriptSection[];
  spriteUrl: string | null;
}

export const MangaViewer: React.FC<MangaViewerProps> = ({ script, spriteUrl }) => {
  const section = script[0];
  if (!section || !section.panels) return <div className="p-8 text-center text-slate-400">No manga script available.</div>;

  // We limit to 8 panels because the sprite sheet is generated as a 2x4 grid
  const panels = section.panels.slice(0, 8);

  const handleDownloadPdf = async () => {
    if (!window.jspdf) {
        alert('PDF library missing');
        return;
    }
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const availableWidth = pageWidth - (margin * 2);
    // Layout: 2 panels per row, 2 rows per page = 4 panels per page.
    const gap = 5;
    const panelWidth = (availableWidth - gap) / 2;
    // Aspect ratio 3:4 (width:height) -> Height = Width * 1.33
    const panelHeight = panelWidth * 1.33;

    // Title Page
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(51, 65, 85); // Slate 700
    const titleLines = doc.splitTextToSize(section.title, availableWidth);
    doc.text(titleLines, pageWidth / 2, 40, { align: "center" });
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.text("Generated by IntelliLearn AI", pageWidth / 2, 55 + (titleLines.length * 5), { align: "center" });

    // Helper: Load Image
    const loadImage = (src: string) => new Promise<HTMLImageElement>((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = "anonymous"; 
        img.onload = () => resolve(img);
        img.onerror = reject;
        img.src = src;
    });

    // Helper: Crop Sprite
    const getPanelImage = (img: HTMLImageElement, col: number, row: number): string | null => {
        const canvas = document.createElement('canvas');
        const sw = img.width / 2;
        const sh = img.height / 4;
        canvas.width = sw;
        canvas.height = sh;
        const ctx = canvas.getContext('2d');
        if(!ctx) return null;
        ctx.drawImage(img, col * sw, row * sh, sw, sh, 0, 0, sw, sh);
        return canvas.toDataURL('image/jpeg', 0.95);
    };

    let imgElement: HTMLImageElement | null = null;
    if (spriteUrl) {
        try {
            imgElement = await loadImage(spriteUrl);
        } catch (e) {
            console.error("Failed to load sprite for PDF", e);
        }
    }

    let yOffset = 80;
    
    // Add first 4 panels to first page if there's space, else start new page
    // 80 + 2 * panelHeight might exceed A4 (297mm).
    // panelWidth approx 90mm -> height 120mm. 2 rows = 240mm. + 80 = 320mm > 297mm.
    // So we need a new page for panels immediately.
    doc.addPage();
    yOffset = margin;

    for (let i = 0; i < panels.length; i++) {
        const panel = panels[i];
        
        // Grid logic for PDF (2 cols x 2 rows = 4 panels per page)
        const itemsPerPage = 4;
        const pageIndex = Math.floor(i / itemsPerPage);
        const indexOnPage = i % itemsPerPage;
        
        const pdfCol = indexOnPage % 2; // 0 or 1
        const pdfRow = Math.floor(indexOnPage / 2); // 0 or 1

        // New Page Check
        if (i > 0 && indexOnPage === 0) {
            doc.addPage();
            yOffset = margin;
        }

        const x = margin + (pdfCol * (panelWidth + gap));
        const y = yOffset + (pdfRow * (panelHeight + gap));

        // Draw Panel Background/Image
        if (imgElement) {
            const spriteCol = i % 2;
            const spriteRow = Math.floor(i / 2); // 0..3
            const panelData = getPanelImage(imgElement, spriteCol, spriteRow);
            if (panelData) {
                doc.addImage(panelData, 'JPEG', x, y, panelWidth, panelHeight);
            }
        } else {
            // Placeholder rect if no image
            doc.setDrawColor(200);
            doc.setFillColor(245);
            doc.rect(x, y, panelWidth, panelHeight, 'FD');
            doc.text("Generating...", x + panelWidth/2, y + panelHeight/2, { align: 'center' });
        }

        // Draw Panel Border
        doc.setDrawColor(0);
        doc.setLineWidth(0.5);
        doc.rect(x, y, panelWidth, panelHeight);

        // Draw Panel Number
        doc.setFillColor(0);
        doc.rect(x, y, 8, 6, 'F');
        doc.setTextColor(255);
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.text(`${i + 1}`, x + 4, y + 4, { align: 'center' });

        // Draw Dialogue Overlays
        doc.setFontSize(8);
        
        // Narrator (Top)
        const narratorLines = panel.dialogue.filter(d => d.speaker.toLowerCase() === 'narrator');
        let narrY = y + 8;
        if (narratorLines.length > 0) {
            narratorLines.forEach(line => {
                doc.setFont("helvetica", "bold");
                const text = doc.splitTextToSize(line.text, panelWidth - 10);
                const h = (text.length * 3) + 4;
                
                doc.setFillColor(255, 255, 220); // Light Yellow
                doc.setDrawColor(50);
                doc.rect(x + 5, narrY, panelWidth - 10, h, 'FD');
                
                doc.setTextColor(0);
                doc.text(text, x + (panelWidth/2), narrY + 4, { align: 'center' });
                narrY += h + 2;
            });
        }

        // Characters (Bottom)
        const charLines = panel.dialogue.filter(d => d.speaker.toLowerCase() !== 'narrator');
        // Stack from bottom up
        let charY = y + panelHeight - 6;
        
        for (let k = charLines.length - 1; k >= 0; k--) {
             const line = charLines[k];
             const isRight = k % 2 !== 0; 
             
             doc.setFont("helvetica", "bold");
             const speakerWidth = doc.getTextWidth(line.speaker);
             
             doc.setFont("helvetica", "normal");
             const maxBubbleWidth = (panelWidth * 0.75);
             const textLines = doc.splitTextToSize(line.text, maxBubbleWidth);
             const bubbleHeight = (textLines.length * 3.5) + 6; // Padding
             
             charY -= bubbleHeight;
             
             const bubbleX = isRight ? (x + panelWidth - maxBubbleWidth - 4) : (x + 4);
             
             // Bubble
             doc.setFillColor(255, 255, 255);
             doc.setDrawColor(0);
             doc.roundedRect(bubbleX, charY, maxBubbleWidth, bubbleHeight, 1, 1, 'FD');
             
             // Speaker Name
             doc.setFontSize(6);
             doc.setFont("helvetica", "bold");
             doc.setTextColor(100);
             doc.text(line.speaker.toUpperCase(), bubbleX + 2, charY + 3);
             
             // Text
             doc.setFontSize(8);
             doc.setFont("helvetica", "normal");
             doc.setTextColor(0);
             doc.text(textLines, bubbleX + 2, charY + 7);
             
             charY -= 2; // Spacing between bubbles
        }
    }

    doc.save('intelli-manga-full.pdf');
  };

  return (
    <div className="w-full max-w-4xl mx-auto">
       <div className="flex justify-between items-center mb-6 bg-white p-4 rounded-xl shadow-sm border border-slate-200">
            <div>
                <h2 className="text-2xl font-black text-slate-800 uppercase tracking-tighter">Manga Mode</h2>
                <p className="text-sm font-bold text-slate-500">{section.title}</p>
            </div>
            <button 
                onClick={handleDownloadPdf}
                className="flex items-center gap-2 px-4 py-2 bg-slate-800 text-white text-sm font-bold uppercase tracking-wide hover:bg-slate-700 transition-colors rounded-lg"
            >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                Download PDF
            </button>
        </div>

        {/* 
            Optimized Sprite Sheet Grid 
            The image is 2 columns x 4 rows.
        */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 bg-slate-100 p-4 rounded-xl shadow-inner">
            {panels.map((panel, index) => {
                // Calculate position in the 2x4 grid
                const colIndex = index % 2; // 0 or 1
                const rowIndex = Math.floor(index / 2); // 0, 1, 2, 3

                const bgPosX = colIndex * 100;
                const bgPosY = rowIndex * (100 / 3); 

                return (
                    <div key={index} className="relative aspect-[3/4] bg-white border-4 border-black shadow-lg overflow-hidden group">
                        
                        {/* The Image Layer (Sprite) */}
                        <div 
                            className="absolute inset-0 bg-no-repeat transition-transform duration-700 group-hover:scale-105"
                            style={{
                                backgroundImage: spriteUrl ? `url(${spriteUrl})` : 'none',
                                backgroundSize: '200% 400%', // 2 cols, 4 rows = image is 200% width, 400% height of one panel
                                backgroundPosition: `${bgPosX}% ${bgPosY}%`,
                                filter: 'grayscale(100%) contrast(110%)'
                            }}
                        >
                            {!spriteUrl && (
                                <div className="absolute inset-0 flex items-center justify-center bg-slate-100 text-slate-400 font-bold">
                                    <div className="text-center p-4">
                                        <Spinner />
                                        <p className="mt-2 text-xs uppercase tracking-widest">Generating Art...</p>
                                    </div>
                                </div>
                            )}
                        </div>

                        {/* Panel Number Tag */}
                        <div className="absolute top-0 left-0 bg-black text-white text-[10px] font-bold px-1.5 py-0.5 z-20">
                            {index + 1}
                        </div>

                        {/* Dialogue Overlay */}
                        <div className="absolute inset-0 pointer-events-none p-2 flex flex-col justify-between">
                            {panel.dialogue.map((line, dIdx) => {
                                const isNarrator = line.speaker.toLowerCase() === 'narrator';
                                return (
                                    <div 
                                        key={dIdx} 
                                        className={`pointer-events-auto max-w-[85%] text-xs sm:text-sm leading-tight
                                            ${isNarrator 
                                                ? 'self-center bg-yellow-50 border border-black p-1 shadow-sm mb-auto mt-2 text-center w-3/4 opacity-90' 
                                                : (dIdx % 2 === 0 ? 'self-start mt-auto mb-4 ml-1' : 'self-end mt-auto mb-8 mr-1')
                                            }
                                        `}
                                    >
                                        {!isNarrator && (
                                            <div className={`bg-white border-2 border-black p-2 shadow-md relative rounded-xl
                                                ${dIdx % 2 === 0 ? 'rounded-bl-none' : 'rounded-br-none'}
                                            `}>
                                                <span className="block text-[9px] font-black text-slate-400 uppercase mb-0.5">{line.speaker}</span>
                                                <span className="text-slate-900 font-medium">{line.text}</span>
                                            </div>
                                        )}
                                        {isNarrator && (
                                            <div>
                                                <span className="font-bold text-slate-800">{line.text}</span>
                                            </div>
                                        )}
                                    </div>
                                )
                            })}
                        </div>
                    </div>
                );
            })}
        </div>
        <p className="text-center text-slate-400 text-xs mt-4">
            AI-generated manga panels • Optimized with CSS Sprites
        </p>
    </div>
  );
};
